name = "nano-workestrator"
compatibility_date = "2023-01-01"

d1_databases = [
  { binding = "DB", database_name = "workestrator", database_id = "" },
]

[durable_objects]
bindings = [
  { name = "DURABLE_OBJECT", class_name = "DurableWorkestrator" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableWorkestrator"]